pages: 
    stages:          # List of stages for jobs, and their order of execution
       - deploy
    script:

    deploy-job:      # This job runs in the deploy stage.
    stage: deploy  
    only: 
        - main# It only runs when *both* jobs in the test stage complete successfully.
    script:
        - echo "Deploying application..."
        - echo "Application successfully deployed."

